In [2]:
# Youtube Video from where I practiced this notebook
# https://www.youtube.com/watch?v=vmEHCJofslg

### Practice your Python Pandas data science skills with problems on StrataScratch!
##### Video Descrioption:

https://stratascratch.com/?via=keith

Join the Python Army to get access to perks!
YouTube - https://www.youtube.com/channel/UCq6X...
Patreon - https://www.patreon.com/keithgalli

Data & code used in this Tutorial: https://github.com/KeithGalli/pandas
Python Pandas Documentation: http://pandas.pydata.org/pandas-docs/...

Let me know if you have any questions!

In this video we walk through many of the fundamental concepts to use the Python Pandas Data Science Library. We start off by installing pandas and loading in an example csv. We then look at different ways to read the data. Read a column, rows, specific cell, etc. Also ways to read data based on conditioning. We then move into some more advanced ways to sort & filter data. We look at making conditional changes to our data. We also start doing aggregate stats using the groupby function. We finished the video talking about how you would work with a very large dataset (many gigabytes)

I realized as I upload this video there are some additional things I want to talk about in a later video. The first thing that comes to mind immediately is using the apply() function on a dataframe to alter the data using a custom or lambda function. If you have questions on this or anything else before I get around to making  a part 2, feel free to write me a note in the comments.

If you enjoyed this video, be sure to throw it a like and make sure to subscribe to not miss any future videos!

Thanks for watching friends! Happy coding! :)

---------------------------------------------
Follow me on social media!
Instagram | https://www.instagram.com/keithgalli/
Twitter | https://twitter.com/keithgalli

---------------------------------------------
Link to original source of data from Kaggle: https://www.kaggle.com/abcsds/pokemon

---------------------------------------------
Video Outline!
- 0:00 - Why Pandas?
- 1:46 - Installing Pandas
- 2:03 - Getting the data used in this video
- 3:50 - Loading the data into Pandas (CSVs, Excel, TXTs, etc.)
- 8:49 - Reading Data (Getting Rows, Columns, Cells, Headers, etc.)
- 13:10 - Iterate through each Row
- 14:11 - Getting rows based on a specific condition
- 15:47 - High Level description of your data (min, max, mean, std dev, etc.)
- 16:24 - Sorting Values (Alphabetically, Numerically)
- 18:19 - Making Changes to the DataFrame
- 18:56 - Adding a column
- 21:22 - Deleting a column
- 22:14 - Summing Multiple Columns to Create new Column.
- 24:14 - Rearranging columns
- 28:06 - Saving our Data (CSV, Excel, TXT, etc.)
- 31:47 - Filtering Data (based on multiple conditions)
- 35:40 - Reset Index
- 37:41 - Regex Filtering (filter based on textual patterns)
- 43:08 - Conditional Changes
- 47:57 - Aggregate Statistics using Groupby (Sum, Mean, Counting)
- 54:53 - Working with large amounts of data (setting chunksize)

-------------------------
If you are curious to learn how I make my tutorials, check out this video: https://youtu.be/LEO4igyXbLs

*I use affiliate links on the products that I recommend. I may earn a purchase commission or a referral bonus from the usage of these links.

In [2]:
# Video Outline!
# 0:00 - Why Pandas?
# 1:46 - Installing Pandas
# 2:03 - Getting the data used in this video
# 3:50 - Loading the data into Pandas (CSVs, Excel, TXTs, etc.)
# 8:49 - Reading Data (Getting Rows, Columns, Cells, Headers, etc.)
# 13:10 - Iterate through each Row
# 14:11 - Getting rows based on a specific condition
# 15:47 - High Level description of your data (min, max, mean, std dev, etc.)
# 16:24 - Sorting Values (Alphabetically, Numerically)
# 18:19 - Making Changes to the DataFrame
# 18:56 - Adding a column
# 21:22 - Deleting a column
# 22:14 - Summing Multiple Columns to Create new Column.
# 24:14 - Rearranging columns
# 28:06 - Saving our Data (CSV, Excel, TXT, etc.)
# 31:47 - Filtering Data (based on multiple conditions)
# 35:40 - Reset Index
# 37:41 - Regex Filtering (filter based on textual patterns)
# 43:08 - Conditional Changes
# 47:57 - Aggregate Statistics using Groupby (Sum, Mean, Counting)
# 54:53 - Working with large amounts of data (setting chunksize)

In [5]:
import pandas as pd

df = pd.read_csv("../../data/pokemon_data.csv")

# if reading .txt file in csv, specify the delimiter to separate columns of data
# df = pd.read_csv("../../data/pokemon_data.txt", delimiter="\t")

df.head(5)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [7]:
# Getting columns
df.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [9]:
# Converting columns into list
list(df.columns)

['#',
 'Name',
 'Type 1',
 'Type 2',
 'HP',
 'Attack',
 'Defense',
 'Sp. Atk',
 'Sp. Def',
 'Speed',
 'Generation',
 'Legendary']

In [13]:
# Read a specific column
# df.Name # If column name consists of 1 word, without special chars. this can be used as well
# OR This can work if there is a space in column name
df["Name"]

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object

In [18]:
# Read Each Row
df.iloc[0:]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False

In [20]:
# Read row ranges
df.iloc[0:4]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False

In [22]:
# Read a specific location (Row, Column)
df.iloc[2, 1]

'Venusaur'

In [34]:
# Iterate through rows one by one
for index, row in df.iterrows():
    print("-----\n", "index:", index, "\n", "row:\n", row, "\n----\n\n")

-----
 index: 0
 row:
 #                     1
Name          Bulbasaur
Type 1            Grass
Type 2           Poison
HP                   45
Attack               49
Defense              49
Sp. Atk              65
Sp. Def              65
Speed                45
Generation            1
Legendary         False
Name: 0, dtype: object
----


-----
 index: 1
 row:
 #                   2
Name          Ivysaur
Type 1          Grass
Type 2         Poison
HP                 60
Attack             62
Defense            63
Sp. Atk            80
Sp. Def            80
Speed              60
Generation          1
Legendary       False
Name: 1, dtype: object
----


-----
 index: 2
 row:
 #                    3
Name          Venusaur
Type 1           Grass
Type 2          Poison
HP                  80
Attack              82
Defense             83
Sp. Atk            100
Sp. Def            100
Speed               80
Generation           1
Legendary        False
Name: 2, dtype: object
----


-----
 index: 3
 row:
 #                                 3
Name          VenusaurMega Venusaur
Type 1                        Grass
Type 2                       Poison
HP                               80
Attack                          100
Defense                         123
Sp. Atk                         122
Sp. Def                         120
Speed                            80
Generation                        1
Legendary                     False
Name: 3, dtype: object
----


-----
 index: 4
 row:
 #                      4
Name          Charmander
Type 1              Fire
Type 2               NaN
HP                    39
Attack                52
Defense               43
Sp. Atk               60
Sp. Def               50
Speed                 65
Generation             1
Legendary          False
Name: 4, dtype: object
----


-----
 index: 5
 row:
 #                      5
Name          Charmeleon
Type 1              Fire
Type 2               NaN
HP                    58
Attack                64
Defense               58
Sp. Atk               80
Sp. Def               65
Speed                 80
Generation             1
Legendary          False
Name: 5, dtype: object
----


-----
 index: 6
 row:
 #                     6
Name          Charizard
Type 1             Fire
Type 2           Flying
HP                   78
Attack               84
Defense              78
Sp. Atk             109
Sp. Def              85
Speed               100
Generation            1
Legendary         False
Name: 6, dtype: object
----


-----
 index: 7
 row:
 #                                     6
Name          CharizardMega Charizard X
Type 1                             Fire
Type 2                           Dragon
HP                                   78
Attack                              130
Defense                             111
Sp. Atk                             130
Sp. Def                              85
Speed                               100
Generation                            1
Legendary                         False
Name: 7, dtype: object
----


-----
 index: 8
 row:
 #                                     6
Name          CharizardMega Charizard Y
Type 1                             Fire
Type 2                           Flying
HP                                   78
Attack                              104
Defense                              78
Sp. Atk                             159
Sp. Def                             115
Speed                               100
Generation                            1
Legendary                         False
Name: 8, dtype: object
----


-----
 index: 9
 row:
 #                    7
Name          Squirtle
Type 1           Water
Type 2             NaN
HP                  44
Attack              48
Defense             65
Sp. Atk             50
Sp. Def             64
Speed               43
Generation           1
Legendary        False
Name: 9, dtype: object
----


-----
 index: 10
 row:
 #                     8
Name          Wartortle
Type 1            Water
Type 2              NaN
HP                   59
Attack               63
Defense              80
Sp. Atk              65
Sp. Def              80
Speed                58
Generation            1
Legendary         False
Name: 10, dtype: object
----


-----
 index: 11
 row:
 #                     9
Name          Blastoise
Type 1            Water
Type 2              NaN
HP                   79
Attack               83
Defense             100
Sp. Atk              85
Sp. Def             105
Speed                78
Generation            1
Legendary         False
Name: 11, dtype: object
----


-----
 index: 12
 row:
 #                                   9
Name          BlastoiseMega Blastoise
Type 1                          Water
Type 2                            NaN
HP                                 79
Attack                            103
Defense                           120
Sp. Atk                           135
Sp. Def                           115
Speed                              78
Generation                          1
Legendary                       False
Name: 12, dtype: object
----


-----
 index: 13
 row:
 #                   10
Name          Caterpie
Type 1             Bug
Type 2             NaN
HP                  45
Attack              30
Defense             35
Sp. Atk             20
Sp. Def             20
Speed               45
Generation           1
Legendary        False
Name: 13, dtype: object
----


-----
 index: 14
 row:
 #                  11
Name          Metapod
Type 1            Bug
Type 2            NaN
HP                 50
Attack             20
Defense            55
Sp. Atk            25
Sp. Def            25
Speed              30
Generation          1
Legendary       False
Name: 14, dtype: object
----


-----
 index: 15
 row:
 #                     12
Name          Butterfree
Type 1               Bug
Type 2            Flying
HP                    60
Attack                45
Defense               50
Sp. Atk               90
Sp. Def               80
Speed                 70
Generation             1
Legendary          False
Name: 15, dtype: object
----


-----
 index: 16
 row:
 #                 13
Name          Weedle
Type 1           Bug
Type 2        Poison
HP                40
Attack            35
Defense           30
Sp. Atk           20
Sp. Def           20
Speed             50
Generation         1
Legendary      False
Name: 16, dtype: object
----


-----
 index: 17
 row:
 #                 14
Name          Kakuna
Type 1           Bug
Type 2        Poison
HP                45
Attack            25
Defense           50
Sp. Atk           25
Sp. Def           25
Speed             35
Generation         1
Legendary      False
Name: 17, dtype: object
----


-----
 index: 18
 row:
 #                   15
Name          Beedrill
Type 1             Bug
Type 2          Poison
HP                  65
Attack              90
Defense             40
Sp. Atk             45
Sp. Def             80
Speed               75
Generation           1
Legendary        False
Name: 18, dtype: object
----


-----
 index: 19
 row:
 #                                15
Name          BeedrillMega Beedrill
Type 1                          Bug
Type 2                       Poison
HP                               65
Attack                          150
Defense                          40
Sp. Atk                          15
Sp. Def                          80
Speed                           145
Generation                        1
Legendary                     False
Name: 19, dtype: object
----


-----
 index: 20
 row:
 #                 16
Name          Pidgey
Type 1        Normal
Type 2        Flying
HP                40
Attack            45
Defense           40
Sp. Atk           35
Sp. Def           35
Speed             56
Generation         1
Legendary      False
Name: 20, dtype: object
----


-----
 index: 21
 row:
 #                    17
Name          Pidgeotto
Type 1           Normal
Type 2           Flying
HP                   63
Attack               60
Defense              55
Sp. Atk              50
Sp. Def              50
Speed                71
Generation            1
Legendary         False
Name: 21, dtype: object
----


-----
 index: 22
 row:
 #                  18
Name          Pidgeot
Type 1         Normal
Type 2         Flying
HP                 83
Attack             80
Defense            75
Sp. Atk            70
Sp. Def            70
Speed             101
Generation          1
Legendary       False
Name: 22, dtype: object
----


-----
 index: 23
 row:
 #                              18
Name          PidgeotMega Pidgeot
Type 1                     Normal
Type 2                     Flying
HP                             83
Attack                         80
Defense                        80
Sp. Atk                       135
Sp. Def                        80
Speed                         121
Generation                      1
Legendary                   False
Name: 23, dtype: object
----


-----
 index: 24
 row:
 #                  19
Name          Rattata
Type 1         Normal
Type 2            NaN
HP                 30
Attack             56
Defense            35
Sp. Atk            25
Sp. Def            35
Speed              72
Generation          1
Legendary       False
Name: 24, dtype: object
----


-----
 index: 25
 row:
 #                   20
Name          Raticate
Type 1          Normal
Type 2             NaN
HP                  55
Attack              81
Defense             60
Sp. Atk             50
Sp. Def             70
Speed               97
Generation           1
Legendary        False
Name: 25, dtype: object
----


-----
 index: 26
 row:
 #                  21
Name          Spearow
Type 1         Normal
Type 2         Flying
HP                 40
Attack             60
Defense            30
Sp. Atk            31
Sp. Def            31
Speed              70
Generation          1
Legendary       False
Name: 26, dtype: object
----


-----
 index: 27
 row:
 #                 22
Name          Fearow
Type 1        Normal
Type 2        Flying
HP                65
Attack            90
Defense           65
Sp. Atk           61
Sp. Def           61
Speed            100
Generation         1
Legendary      False
Name: 27, dtype: object
----


-----
 index: 28
 row:
 #                 23
Name           Ekans
Type 1        Poison
Type 2           NaN
HP                35
Attack            60
Defense           44
Sp. Atk           40
Sp. Def           54
Speed             55
Generation         1
Legendary      False
Name: 28, dtype: object
----


-----
 index: 29
 row:
 #                 24
Name           Arbok
Type 1        Poison
Type 2           NaN
HP                60
Attack            85
Defense           69
Sp. Atk           65
Sp. Def           79
Speed             80
Generation         1
Legendary      False
Name: 29, dtype: object
----


-----
 index: 30
 row:
 #                   25
Name           Pikachu
Type 1        Electric
Type 2             NaN
HP                  35
Attack              55
Defense             40
Sp. Atk             50
Sp. Def             50
Speed               90
Generation           1
Legendary        False
Name: 30, dtype: object
----


-----
 index: 31
 row:
 #                   26
Name            Raichu
Type 1        Electric
Type 2             NaN
HP                  60
Attack              90
Defense             55
Sp. Atk             90
Sp. Def             80
Speed              110
Generation           1
Legendary        False
Name: 31, dtype: object
----


-----
 index: 32
 row:
 #                    27
Name          Sandshrew
Type 1           Ground
Type 2              NaN
HP                   50
Attack               75
Defense              85
Sp. Atk              20
Sp. Def              30
Speed                40
Generation            1
Legendary         False
Name: 32, dtype: object
----


-----
 index: 33
 row:
 #                    28
Name          Sandslash
Type 1           Ground
Type 2              NaN
HP                   75
Attack              100
Defense             110
Sp. Atk              45
Sp. Def              55
Speed                65
Generation            1
Legendary         False
Name: 33, dtype: object
----


-----
 index: 34
 row:
 #                           29
Name          Nidoran (Female)
Type 1                  Poison
Type 2                     NaN
HP                          55
Attack                      47
Defense                     52
Sp. Atk                     40
Sp. Def                     40
Speed                       41
Generation                   1
Legendary                False
Name: 34, dtype: object
----


-----
 index: 35
 row:
 #                   30
Name          Nidorina
Type 1          Poison
Type 2             NaN
HP                  70
Attack              62
Defense             67
Sp. Atk             55
Sp. Def             55
Speed               56
Generation           1
Legendary        False
Name: 35, dtype: object
----


-----
 index: 36
 row:
 #                    31
Name          Nidoqueen
Type 1           Poison
Type 2           Ground
HP                   90
Attack               92
Defense              87
Sp. Atk              75
Sp. Def              85
Speed                76
Generation            1
Legendary         False
Name: 36, dtype: object
----


-----
 index: 37
 row:
 #                         32
Name          Nidoran (Male)
Type 1                Poison
Type 2                   NaN
HP                        46
Attack                    57
Defense                   40
Sp. Atk                   40
Sp. Def                   40
Speed                     50
Generation                 1
Legendary              False
Name: 37, dtype: object
----


-----
 index: 38
 row:
 #                   33
Name          Nidorino
Type 1          Poison
Type 2             NaN
HP                  61
Attack              72
Defense             57
Sp. Atk             55
Sp. Def             55
Speed               65
Generation           1
Legendary        False
Name: 38, dtype: object
----


-----
 index: 39
 row:
 #                   34
Name          Nidoking
Type 1          Poison
Type 2          Ground
HP                  81
Attack             102
Defense             77
Sp. Atk             85
Sp. Def             75
Speed               85
Generation           1
Legendary        False
Name: 39, dtype: object
----


-----
 index: 40
 row:
 #                   35
Name          Clefairy
Type 1           Fairy
Type 2             NaN
HP                  70
Attack              45
Defense             48
Sp. Atk             60
Sp. Def             65
Speed               35
Generation           1
Legendary        False
Name: 40, dtype: object
----


-----
 index: 41
 row:
 #                   36
Name          Clefable
Type 1           Fairy
Type 2             NaN
HP                  95
Attack              70
Defense             73
Sp. Atk             95
Sp. Def             90
Speed               60
Generation           1
Legendary        False
Name: 41, dtype: object
----


-----
 index: 42
 row:
 #                 37
Name          Vulpix
Type 1          Fire
Type 2           NaN
HP                38
Attack            41
Defense           40
Sp. Atk           50
Sp. Def           65
Speed             65
Generation         1
Legendary      False
Name: 42, dtype: object
----


-----
 index: 43
 row:
 #                    38
Name          Ninetales
Type 1             Fire
Type 2              NaN
HP                   73
Attack               76
Defense              75
Sp. Atk              81
Sp. Def             100
Speed               100
Generation            1
Legendary         False
Name: 43, dtype: object
----


-----
 index: 44
 row:
 #                     39
Name          Jigglypuff
Type 1            Normal
Type 2             Fairy
HP                   115
Attack                45
Defense               20
Sp. Atk               45
Sp. Def               25
Speed                 20
Generation             1
Legendary          False
Name: 44, dtype: object
----


-----
 index: 45
 row:
 #                     40
Name          Wigglytuff
Type 1            Normal
Type 2             Fairy
HP                   140
Attack                70
Defense               45
Sp. Atk               85
Sp. Def               50
Speed                 45
Generation             1
Legendary          False
Name: 45, dtype: object
----


-----
 index: 46
 row:
 #                 41
Name           Zubat
Type 1        Poison
Type 2        Flying
HP                40
Attack            45
Defense           35
Sp. Atk           30
Sp. Def           40
Speed             55
Generation         1
Legendary      False
Name: 46, dtype: object
----


-----
 index: 47
 row:
 #                 42
Name          Golbat
Type 1        Poison
Type 2        Flying
HP                75
Attack            80
Defense           70
Sp. Atk           65
Sp. Def           75
Speed             90
Generation         1
Legendary      False
Name: 47, dtype: object
----


-----
 index: 48
 row:
 #                 43
Name          Oddish
Type 1         Grass
Type 2        Poison
HP                45
Attack            50
Defense           55
Sp. Atk           75
Sp. Def           65
Speed             30
Generation         1
Legendary      False
Name: 48, dtype: object
----


-----
 index: 49
 row:
 #                 44
Name           Gloom
Type 1         Grass
Type 2        Poison
HP                60
Attack            65
Defense           70
Sp. Atk           85
Sp. Def           75
Speed             40
Generation         1
Legendary      False
Name: 49, dtype: object
----


-----
 index: 50
 row:
 #                    45
Name          Vileplume
Type 1            Grass
Type 2           Poison
HP                   75
Attack               80
Defense              85
Sp. Atk             110
Sp. Def              90
Speed                50
Generation            1
Legendary         False
Name: 50, dtype: object
----


-----
 index: 51
 row:
 #                46
Name          Paras
Type 1          Bug
Type 2        Grass
HP               35
Attack           70
Defense          55
Sp. Atk          45
Sp. Def          55
Speed            25
Generation        1
Legendary     False
Name: 51, dtype: object
----


-----
 index: 52
 row:
 #                   47
Name          Parasect
Type 1             Bug
Type 2           Grass
HP                  60
Attack              95
Defense             80
Sp. Atk             60
Sp. Def             80
Speed               30
Generation           1
Legendary        False
Name: 52, dtype: object
----


-----
 index: 53
 row:
 #                  48
Name          Venonat
Type 1            Bug
Type 2         Poison
HP                 60
Attack             55
Defense            50
Sp. Atk            40
Sp. Def            55
Speed              45
Generation          1
Legendary       False
Name: 53, dtype: object
----


-----
 index: 54
 row:
 #                   49
Name          Venomoth
Type 1             Bug
Type 2          Poison
HP                  70
Attack              65
Defense             60
Sp. Atk             90
Sp. Def             75
Speed               90
Generation           1
Legendary        False
Name: 54, dtype: object
----


-----
 index: 55
 row:
 #                  50
Name          Diglett
Type 1         Ground
Type 2            NaN
HP                 10
Attack             55
Defense            25
Sp. Atk            35
Sp. Def            45
Speed              95
Generation          1
Legendary       False
Name: 55, dtype: object
----


-----
 index: 56
 row:
 #                  51
Name          Dugtrio
Type 1         Ground
Type 2            NaN
HP                 35
Attack             80
Defense            50
Sp. Atk            50
Sp. Def            70
Speed             120
Generation          1
Legendary       False
Name: 56, dtype: object
----


-----
 index: 57
 row:
 #                 52
Name          Meowth
Type 1        Normal
Type 2           NaN

In [40]:
# Iterate through rows one by one and read Specific column value
for index, row in df.iterrows():
    print(index, row["Name"], " | ", row["Type 1"])

0 Bulbasaur  |  Grass
1 Ivysaur  |  Grass
2 Venusaur  |  Grass
3 VenusaurMega Venusaur  |  Grass
4 Charmander  |  Fire
5 Charmeleon  |  Fire
6 Charizard  |  Fire
7 CharizardMega Charizard X  |  Fire
8 CharizardMega Charizard Y  |  Fire
9 Squirtle  |  Water
10 Wartortle  |  Water
11 Blastoise  |  Water
12 BlastoiseMega Blastoise  |  Water
13 Caterpie  |  Bug
14 Metapod  |  Bug
15 Butterfree  |  Bug
16 Weedle  |  Bug
17 Kakuna  |  Bug
18 Beedrill  |  Bug
19 BeedrillMega Beedrill  |  Bug
20 Pidgey  |  Normal
21 Pidgeotto  |  Normal
22 Pidgeot  |  Normal
23 PidgeotMega Pidgeot  |  Normal
24 Rattata  |  Normal
25 Raticate  |  Normal
26 Spearow  |  Normal
27 Fearow  |  Normal
28 Ekans  |  Poison
29 Arbok  |  Poison
30 Pikachu  |  Electric
31 Raichu  |  Electric
32 Sandshrew  |  Ground
33 Sandslash  |  Ground
34 Nidoran (Female)  |  Poison
35 Nidorina  |  Poison
36 Nidoqueen  |  Poison
37 Nidoran (Male)  |  Poison
38 Nidorino  |  Poison
39 Nidoking  |  Poison
40 Clefairy  |  Fairy
41 Clefable  |  Fairy
42 Vulpix  |  Fire
43 Ninetales  |  Fire
44 Jigglypuff  |  Normal
45 Wigglytuff  |  Normal
46 Zubat  |  Poison
47 Golbat  |  Poison
48 Oddish  |  Grass
49 Gloom  |  Grass
50 Vileplume  |  Grass
51 Paras  |  Bug
52 Parasect  |  Bug
53 Venonat  |  Bug
54 Venomoth  |  Bug
55 Diglett  |  Ground
56 Dugtrio  |  Ground
57 Meowth  |  Normal
58 Persian  |  Normal
59 Psyduck  |  Water
60 Golduck  |  Water
61 Mankey  |  Fighting
62 Primeape  |  Fighting
63 Growlithe  |  Fire
64 Arcanine  |  Fire
65 Poliwag  |  Water
66 Poliwhirl  |  Water
67 Poliwrath  |  Water
68 Abra  |  Psychic
69 Kadabra  |  Psychic
70 Alakazam  |  Psychic
71 AlakazamMega Alakazam  |  Psychic
72 Machop  |  Fighting
73 Machoke  |  Fighting
74 Machamp  |  Fighting
75 Bellsprout  |  Grass
76 Weepinbell  |  Grass
77 Victreebel  |  Grass
78 Tentacool  |  Water
79 Tentacruel  |  Water
80 Geodude  |  Rock
81 Graveler  |  Rock
82 Golem  |  Rock
83 Ponyta  |  Fire
84 Rapidash  |  Fire
85 Slowpoke  |  Water
86 Slowbro  |  Water
87 SlowbroMega Slowbro  |  Water
88 Magnemite  |  Electric
89 Magneton  |  Electric
90 Farfetch'd  |  Normal
91 Doduo  |  Normal
92 Dodrio  |  Normal
93 Seel  |  Water
94 Dewgong  |  Water
95 Grimer  |  Poison
96 Muk  |  Poison
97 Shellder  |  Water
98 Cloyster  |  Water
99 Gastly  |  Ghost
100 Haunter  |  Ghost
101 Gengar  |  Ghost
102 GengarMega Gengar  |  Ghost
103 Onix  |  Rock
104 Drowzee  |  Psychic
105 Hypno  |  Psychic
106 Krabby  |  Water
107 Kingler  |  Water
108 Voltorb  |  Electric
109 Electrode  |  Electric
110 Exeggcute  |  Grass
111 Exeggutor  |  Grass
112 Cubone  |  Ground
113 Marowak  |  Ground
114 Hitmonlee  |  Fighting
115 Hitmonchan  |  Fighting
116 Lickitung  |  Normal
117 Koffing  |  Poison
118 Weezing  |  Poison
119 Rhyhorn  |  Ground
120 Rhydon  |  Ground
121 Chansey  |  Normal
122 Tangela  |  Grass
123 Kangaskhan  |  Normal
124 KangaskhanMega Kangaskhan  |  Normal
125 Horsea  |  Water
126 Seadra  |  Water
127 Goldeen  |  Water
128 Seaking  |  Water
129 Staryu  |  Water
130 Starmie  |  Water
131 Mr. Mime  |  Psychic
132 Scyther  |  Bug
133 Jynx  |  Ice
134 Electabuzz  |  Electric
135 Magmar  |  Fire
136 Pinsir  |  Bug
137 PinsirMega Pinsir  |  Bug
138 Tauros  |  Normal
139 Magikarp  |  Water
140 Gyarados  |  Water
141 GyaradosMega Gyarados  |  Water
142 Lapras  |  Water
143 Ditto  |  Normal
144 Eevee  |  Normal
145 Vaporeon  |  Water
146 Jolteon  |  Electric
147 Flareon  |  Fire
148 Porygon  |  Normal
149 Omanyte  |  Rock
150 Omastar  |  Rock
151 Kabuto  |  Rock
152 Kabutops  |  Rock
153 Aerodactyl  |  Rock
154 AerodactylMega Aerodactyl  |  Rock
155 Snorlax  |  Normal
156 Articuno  |  Ice
157 Zapdos  |  Electric
158 Moltres  |  Fire
159 Dratini  |  Dragon
160 Dragonair  |  Dragon
161 Dragonite  |  Dragon
162 Mewtwo  |  Psychic
163 MewtwoMega Mewtwo X  |  Psychic
164 MewtwoMega Mewtwo Y  |  Psychic
165 Mew  |  Psychic
166 Chikorita  |  Grass
167 Bayleef  |  Grass
168 Meganium  |  Grass
169 Cyndaquil  |  Fire
170 Quilava  |  Fire
171 Typhlosion  |  Fire
172 Totodile  |  Water
173 Croconaw  |  Water
174 Feraligatr  |  Water
175 Sentret  |  Normal
176 Furret  |  Normal
177 Hoothoot  |  Normal
178 Noctowl  |  Normal
179 Ledyba  |  Bug
180 Ledian  |  Bug
181 Spinarak  |  Bug
182 Ariados  |  Bug
183 Crobat  |  Poison
184 Chinchou  |  Water
185 Lanturn  |  Water
186 Pichu  |  Electric
187 Cleffa  |  Fairy
188 Igglybuff  |  Normal
189 Togepi  |  Fairy
190 Togetic  |  Fairy
191 Natu  |  Psychic
192 Xatu  |  Psychic
193 Mareep  |  Electric
194 Flaaffy  |  Electric
195 Ampharos  |  Electric
196 AmpharosMega Ampharos  |  Electric
197 Bellossom  |  Grass
198 Marill  |  Water
199 Azumarill  |  Water
200 Sudowoodo  |  Rock
201 Politoed  |  Water
202 Hoppip  |  Grass
203 Skiploom  |  Grass
204 Jumpluff  |  Grass
205 Aipom  |  Normal
206 Sunkern  |  Grass
207 Sunflora  |  Grass
208 Yanma  |  Bug
209 Wooper  |  Water
210 Quagsire  |  Water
211 Espeon  |  Psychic
212 Umbreon  |  Dark
213 Murkrow  |  Dark
214 Slowking  |  Water
215 Misdreavus  |  Ghost
216 Unown  |  Psychic
217 Wobbuffet  |  Psychic
218 Girafarig  |  Normal
219 Pineco  |  Bug
220 Forretress  |  Bug
221 Dunsparce  |  Normal
222 Gligar  |  Ground
223 Steelix  |  Steel
224 SteelixMega Steelix  |  Steel
225 Snubbull  |  Fairy
226 Granbull  |  Fairy
227 Qwilfish  |  Water
228 Scizor  |  Bug
229 ScizorMega Scizor  |  Bug
230 Shuckle  |  Bug
231 Heracross  |  Bug
232 HeracrossMega Heracross  |  Bug
233 Sneasel  |  Dark
234 Teddiursa  |  Normal
235 Ursaring  |  Normal
236 Slugma  |  Fire
237 Magcargo  |  Fire
238 Swinub  |  Ice
239 Piloswine  |  Ice
240 Corsola  |  Water
241 Remoraid  |  Water
242 Octillery  |  Water
243 Delibird  |  Ice
244 Mantine  |  Water
245 Skarmory  |  Steel
246 Houndour  |  Dark
247 Houndoom  |  Dark
248 HoundoomMega Houndoom  |  Dark
249 Kingdra  |  Water
250 Phanpy  |  Ground
251 Donphan  |  Ground
252 Porygon2  |  Normal
253 Stantler  |  Normal
254 Smeargle  |  Normal
255 Tyrogue  |  Fighting
256 Hitmontop  |  Fighting
257 Smoochum  |  Ice
258 Elekid  |  Electric
259 Magby  |  Fire
260 Miltank  |  Normal
261 Blissey  |  Normal
262 Raikou  |  Electric
263 Entei  |  Fire
264 Suicune  |  Water
265 Larvitar  |  Rock
266 Pupitar  |  Rock
267 Tyranitar  |  Rock
268 TyranitarMega Tyranitar  |  Rock
269 Lugia  |  Psychic
270 Ho-oh  |  Fire
271 Celebi  |  Psychic
272 Treecko  |  Grass
273 Grovyle  |  Grass
274 Sceptile  |  Grass
275 SceptileMega Sceptile  |  Grass
276 Torchic  |  Fire
277 Combusken  |  Fire
278 Blaziken  |  Fire
279 BlazikenMega Blaziken  |  Fire
280 Mudkip  |  Water
281 Marshtomp  |  Water
282 Swampert  |  Water
283 SwampertMega Swampert  |  Water
284 Poochyena  |  Dark
285 Mightyena  |  Dark
286 Zigzagoon  |  Normal
287 Linoone  |  Normal
288 Wurmple  |  Bug
289 Silcoon  |  Bug
290 Beautifly  |  Bug
291 Cascoon  |  Bug
292 Dustox  |  Bug
293 Lotad  |  Water
294 Lombre  |  Water
295 Ludicolo  |  Water
296 Seedot  |  Grass
297 Nuzleaf  |  Grass
298 Shiftry  |  Grass
299 Taillow  |  Normal
300 Swellow  |  Normal
301 Wingull  |  Water
302 Pelipper  |  Water
303 Ralts  |  Psychic
304 Kirlia  |  Psychic
305 Gardevoir  |  Psychic
306 GardevoirMega Gardevoir  |  Psychic
307 Surskit  |  Bug
308 Masquerain  |  Bug
309 Shroomish  |  Grass
310 Breloom  |  Grass
311 Slakoth  |  Normal
312 Vigoroth  |  Normal
313 Slaking  |  Normal
314 Nincada  |  Bug
315 Ninjask  |  Bug
316 Shedinja  |  Bug
317 Whismur  |  Normal
318 Loudred  |  Normal
319 Exploud  |  Normal
320 Makuhita  |  Fighting
321 Hariyama  |  Fighting
322 Azurill  |  Normal
323 Nosepass  |  Rock
324 Skitty  |  Normal
325 Delcatty  |  Normal
326 Sableye  |  Dark
327 SableyeMega Sableye  |  Dark
328 Mawile  |  Steel
329 MawileMega Mawile  |  Steel
330 Aron  |  Steel
331 Lairon  |  Steel
332 Aggron  |  Steel
333 AggronMega Aggron  |  Steel
334 Meditite  |  Fighting
335 Medicham  |  Fighting
336 MedichamMega Medicham  |  Fighting
337 Electrike  |  Electric
338 Manectric  |  Electric
339 ManectricMega Manectric  |  Electric
340 Plusle  |  Electric
341 Minun  |  Electric
342 Volbeat  |  Bug
343 Illumise  |  Bug
344 Roselia  |  Grass
345 Gulpin  |  Poison
346 Swalot  |  Poison
347 Carvanha  |  Water
348 Sharpedo  |  Water
349 SharpedoMega Sharpedo  |  Water
350 Wailmer  |  Water
351 Wailord  |  Water
352 Numel  |  Fire
353 Camerupt  |  Fire
354 CameruptMega Camerupt  |  Fire
355 Torkoal  |  Fire
356 Spoink  |  Psychic
357 Grumpig  |  Psychic
358 Spinda  |  Normal
359 Trapinch  |  Ground
360 Vibrava  |  Ground
361 Flygon  |  Ground
362 Cacnea  |  Grass
363 Cacturne  |  Grass
364 Swablu  |  Normal
365 Altaria  |  Dragon
366 AltariaMega Altaria  |  Dragon
367 Zangoose  |  Normal
368 Seviper  |  Poison
369 Lunatone  |  Rock
370 Solrock  |  Rock
371 Barboach  |  Water
372 Whiscash  |  Water
373 Corphish  |  Water
374 Crawdaunt  |  Water
375 Baltoy  |  Ground
376 Claydol  |  Ground
377 Lileep  |  Rock
378 Cradily  |  Rock
379 Anorith  |  Rock
380 Armaldo  |  Rock
381 Feebas  |  Water
382 Milotic  |  Water
383 Castform  |  Normal
384 Kecleon  |  Normal
385 Shuppet  |  Ghost
386 Banette  |  Ghost
387 BanetteMega Banette  |  Ghost
388 Duskull  |  Ghost
389 Dusclops  |  Ghost
390 Tropius  |  Grass
391 Chimecho  |  Psychic
392 Absol  |  Dark
393 AbsolMega Absol  |  Dark
394 Wynaut  |  Psychic
395 Snorunt  |  Ice
396 Glalie  |  Ice
397 GlalieMega Glalie  |  Ice
398 Spheal  |  Ice
399 Sealeo  |  Ice
400 Walrein  |  Ice
401 Clamperl  |  Water
402 Huntail  |  Water
403 Gorebyss  |  Water
404 Relicanth  |  Water
405 Luvdisc  |  Water
406 Bagon  |  Dragon
407 Shelgon  |  Dragon
408 Salamence  |  Dragon
409 SalamenceMega Salamence  |  Dragon
410 Beldum  |  Steel
411 Metang  |  Steel
412 Metagross  |  Steel
413 MetagrossMega Metagross  |  Steel
414 Regirock  |  Rock
415 Regice  |  Ice
416 Registeel  |  Steel
417 Latias  |  Dragon
418 LatiasMega Latias  |  Dragon
419 Latios  |  Dragon
420 LatiosMega Latios  |  Dragon
421 Kyogre  |  Water
422 KyogrePrimal Kyogre  |  Water
423 Groudon  |  Ground
424 GroudonPrimal Groudon  |  Ground
425 Rayquaza  |  Dragon
426 RayquazaMega Rayquaza  |  Dragon
427 Jirachi  |  Steel
428 DeoxysNormal Forme  |  Psychic
429 DeoxysAttack Forme  |  Psychic
430 DeoxysDefense Forme  |  Psychic
431 DeoxysSpeed Forme  |  Psychic
432 Turtwig  |  Grass
433 Grotle  |  Grass
434 Torterra  |  Grass
435 Chimchar  |  Fire
436 Monferno  |  Fire
437 Infernape  |  Fire
438 Piplup  |  Water
439 Prinplup  |  Water
440 Empoleon  |  Water
441 Starly  |  Normal
442 Staravia  |  Normal
443 Staraptor  |  Normal
444 Bidoof  |  Normal
445 Bibarel  |  Normal
446 Kricketot  |  Bug
447 Kricketune  |  Bug
448 Shinx  |  Electric
449 Luxio  |  Electric
450 Luxray  |  Electric
451 Budew  |  Grass
452 Roserade  |  Grass
453 Cranidos  |  Rock
454 Rampardos  |  Rock
455 Shieldon  |  Rock
456 Bastiodon  |  Rock
457 Burmy  |  Bug
458 WormadamPlant Cloak  |  Bug
459 WormadamSandy Cloak  |  Bug
460 WormadamTrash Cloak  |  Bug
461 Mothim  |  Bug
462 Combee  |  Bug
463 Vespiquen  |  Bug
464 Pachirisu  |  Electric
465 Buizel  |  Water
466 Floatzel  |  Water
467 Cherubi  |  Grass
468 Cherrim  |  Grass
469 Shellos  |  Water
470 Gastrodon  |  Water
471 Ambipom  |  Normal
472 Drifloon  |  Ghost
473 Drifblim  |  Ghost
474 Buneary  |  Normal
475 Lopunny  |  Normal
476 LopunnyMega Lopunny  |  Normal
477 Mismagius  |  Ghost
478 Honchkrow  |  Dark
479 Glameow  |  Normal
480 Purugly  |  Normal
481 Chingling  |  Psychic
482 Stunky  |  Poison
483 Skuntank  |  Poison
484 Bronzor  |  Steel
485 Bronzong  |  Steel
486 Bonsly  |  Rock
487 Mime Jr.  |  Psychic
488 Happiny  |  Normal
489 Chatot  |  Normal
490 Spiritomb  |  Ghost
491 Gible  |  Dragon
492 Gabite  |  Dragon
493 Garchomp  |  Dragon
494 GarchompMega Garchomp  |  Dragon
495 Munchlax  |  Normal
496 Riolu  |  Fighting
497 Lucario  |  Fighting
498 LucarioMega Lucario  |  Fighting
499 Hippopotas  |  Ground
500 Hippowdon  |  Ground
501 Skorupi  |  Poison
502 Drapion  |  Poison
503 Croagunk  |  Poison
504 Toxicroak  |  Poison
505 Carnivine  |  Grass
506 Finneon  |  Water
507 Lumineon  |  Water
508 Mantyke  |  Water
509 Snover  |  Grass
510 Abomasnow  |  Grass
511 AbomasnowMega Abomasnow  |  Grass
512 Weavile  |  Dark
513 Magnezone  |  Electric
514 Lickilicky  |  Normal
515 Rhyperior  |  Ground
516 Tangrowth  |  Grass
517 Electivire  |  Electric
518 Magmortar  |  Fire
519 Togekiss  |  Fairy
520 Yanmega  |  Bug
521 Leafeon  |  Grass
522 Glaceon  |  Ice
523 Gliscor  |  Ground
524 Mamoswine  |  Ice
525 Porygon-Z  |  Normal
526 Gallade  |  Psychic
527 GalladeMega Gallade  |  Psychic
528 Probopass  |  Rock
529 Dusknoir  |  Ghost
530 Froslass  |  Ice
531 Rotom  |  Electric
532 RotomHeat Rotom  |  Electric
533 RotomWash Rotom  |  Electric
534 RotomFrost Rotom  |  Electric
535 RotomFan Rotom  |  Electric
536 RotomMow Rotom  |  Electric
537 Uxie  |  Psychic
538 Mesprit  |  Psychic
539 Azelf  |  Psychic
540 Dialga  |  Steel
541 Palkia  |  Water
542 Heatran  |  Fire
543 Regigigas  |  Normal
544 GiratinaAltered Forme  |  Ghost
545 GiratinaOrigin Forme  |  Ghost
546 Cresselia  |  Psychic
547 Phione  |  Water
548 Manaphy  |  Water
549 Darkrai  |  Dark
550 ShayminLand Forme  |  Grass
551 ShayminSky Forme  |  Grass
552 Arceus  |  Normal
553 Victini  |  Psychic
554 Snivy  |  Grass
555 Servine  |  Grass
556 Serperior  |  Grass
557 Tepig  |  Fire
558 Pignite  |  Fire
559 Emboar  |  Fire
560 Oshawott  |  Water
561 Dewott  |  Water
562 Samurott  |  Water
563 Patrat  |  Normal
564 Watchog  |  Normal
565 Lillipup  |  Normal
566 Herdier  |  Normal
567 Stoutland  |  Normal
568 Purrloin  |  Dark
569 Liepard  |  Dark
570 Pansage  |  Grass
571 Simisage  |  Grass
572 Pansear  |  Fire
573 Simisear  |  Fire
574 Panpour  |  Water
575 Simipour  |  Water
576 Munna  |  Psychic
577 Musharna  |  Psychic
578 Pidove  |  Normal
579 Tranquill  |  Normal
580 Unfezant  |  Normal
581 Blitzle  |  Electric
582 Zebstrika  |  Electric
583 Roggenrola  |  Rock
584 Boldore  |  Rock
585 Gigalith  |  Rock
586 Woobat  |  Psychic
587 Swoobat  |  Psychic
588 Drilbur  |  Ground
589 Excadrill  |  Ground
590 Audino  |  Normal
591 AudinoMega Audino  |  Normal
592 Timburr  |  Fighting
593 Gurdurr  |  Fighting
594 Conkeldurr  |  Fighting
595 Tympole  |  Water
596 Palpitoad  |  Water
597 Seismitoad  |  Water
598 Throh  |  Fighting
599 Sawk  |  Fighting
600 Sewaddle  |  Bug
601 Swadloon  |  Bug
602 Leavanny  |  Bug
603 Venipede  |  Bug
604 Whirlipede  |  Bug
605 Scolipede  |  Bug
606 Cottonee  |  Grass
607 Whimsicott  |  Grass
608 Petilil  |  Grass
609 Lilligant  |  Grass
610 Basculin  |  Water
611 Sandile  |  Ground
612 Krokorok  |  Ground
613 Krookodile  |  Ground
614 Darumaka  |  Fire
615 DarmanitanStandard Mode  |  Fire
616 DarmanitanZen Mode  |  Fire
617 Maractus  |  Grass
618 Dwebble  |  Bug
619 Crustle  |  Bug
620 Scraggy  |  Dark
621 Scrafty  |  Dark
622 Sigilyph  |  Psychic
623 Yamask  |  Ghost
624 Cofagrigus  |  Ghost
625 Tirtouga  |  Water
626 Carracosta  |  Water
627 Archen  |  Rock
628 Archeops  |  Rock
629 Trubbish  |  Poison
630 Garbodor  |  Poison
631 Zorua  |  Dark
632 Zoroark  |  Dark
633 Minccino  |  Normal
634 Cinccino  |  Normal
635 Gothita  |  Psychic
636 Gothorita  |  Psychic
637 Gothitelle  |  Psychic
638 Solosis  |  Psychic
639 Duosion  |  Psychic
640 Reuniclus  |  Psychic
641 Ducklett  |  Water
642 Swanna  |  Water
643 Vanillite  |  Ice
644 Vanillish  |  Ice
645 Vanilluxe  |  Ice
646 Deerling  |  Normal
647 Sawsbuck  |  Normal
648 Emolga  |  Electric
649 Karrablast  |  Bug
650 Escavalier  |  Bug
651 Foongus  |  Grass
652 Amoonguss  |  Grass
653 Frillish  |  Water
654 Jellicent  |  Water
655 Alomomola  |  Water
656 Joltik  |  Bug
657 Galvantula  |  Bug
658 Ferroseed  |  Grass
659 Ferrothorn  |  Grass
660 Klink  |  Steel
661 Klang  |  Steel
662 Klinklang  |  Steel
663 Tynamo  |  Electric
664 Eelektrik  |  Electric
665 Eelektross  |  Electric
666 Elgyem  |  Psychic
667 Beheeyem  |  Psychic
668 Litwick  |  Ghost
669 Lampent  |  Ghost
670 Chandelure  |  Ghost
671 Axew  |  Dragon
672 Fraxure  |  Dragon
673 Haxorus  |  Dragon
674 Cubchoo  |  Ice
675 Beartic  |  Ice
676 Cryogonal  |  Ice
677 Shelmet  |  Bug
678 Accelgor  |  Bug
679 Stunfisk  |  Ground
680 Mienfoo  |  Fighting
681 Mienshao  |  Fighting
682 Druddigon  |  Dragon
683 Golett  |  Ground
684 Golurk  |  Ground
685 Pawniard  |  Dark
686 Bisharp  |  Dark
687 Bouffalant  |  Normal
688 Rufflet  |  Normal
689 Braviary  |  Normal
690 Vullaby  |  Dark
691 Mandibuzz  |  Dark
692 Heatmor  |  Fire
693 Durant  |  Bug
694 Deino  |  Dark
695 Zweilous  |  Dark
696 Hydreigon  |  Dark
697 Larvesta  |  Bug
698 Volcarona  |  Bug
699 Cobalion  |  Steel
700 Terrakion  |  Rock
701 Virizion  |  Grass
702 TornadusIncarnate Forme  |  Flying
703 TornadusTherian Forme  |  Flying
704 ThundurusIncarnate Forme  |  Electric
705 ThundurusTherian Forme  |  Electric
706 Reshiram  |  Dragon
707 Zekrom  |  Dragon
708 LandorusIncarnate Forme  |  Ground
709 LandorusTherian Forme  |  Ground
710 Kyurem  |  Dragon
711 KyuremBlack Kyurem  |  Dragon
712 KyuremWhite Kyurem  |  Dragon
713 KeldeoOrdinary Forme  |  Water
714 KeldeoResolute Forme  |  Water
715 MeloettaAria Forme  |  Normal
716 MeloettaPirouette Forme  |  Normal
717 Genesect  |  Bug
718 Chespin  |  Grass
719 Quilladin  |  Grass
720 Chesnaught  |  Grass
721 Fennekin  |  Fire
722 Braixen  |  Fire
723 Delphox  |  Fire
724 Froakie  |  Water
725 Frogadier  |  Water
726 Greninja  |  Water
727 Bunnelby  |  Normal
728 Diggersby  |  Normal
729 Fletchling  |  Normal
730 Fletchinder  |  Fire
731 Talonflame  |  Fire
732 Scatterbug  |  Bug
733 Spewpa  |  Bug
734 Vivillon  |  Bug
735 Litleo  |  Fire
736 Pyroar  |  Fire
737 Flabébé  |  Fairy
738 Floette  |  Fairy
739 Florges  |  Fairy
740 Skiddo  |  Grass
741 Gogoat  |  Grass
742 Pancham  |  Fighting
743 Pangoro  |  Fighting
744 Furfrou  |  Normal
745 Espurr  |  Psychic
746 MeowsticMale  |  Psychic
747 MeowsticFemale  |  Psychic
748 Honedge  |  Steel
749 Doublade  |  Steel
750 AegislashBlade Forme  |  Steel
751 AegislashShield Forme  |  Steel
752 Spritzee  |  Fairy
753 Aromatisse  |  Fairy
754 Swirlix  |  Fairy
755 Slurpuff  |  Fairy
756 Inkay  |  Dark
757 Malamar  |  Dark
758 Binacle  |  Rock
759 Barbaracle  |  Rock
760 Skrelp  |  Poison
761 Dragalge  |  Poison
762 Clauncher  |  Water
763 Clawitzer  |  Water
764 Helioptile  |  Electric
765 Heliolisk  |  Electric
766 Tyrunt  |  Rock
767 Tyrantrum  |  Rock
768 Amaura  |  Rock
769 Aurorus  |  Rock
770 Sylveon  |  Fairy
771 Hawlucha  |  Fighting
772 Dedenne  |  Electric
773 Carbink  |  Rock
774 Goomy  |  Dragon
775 Sliggoo  |  Dragon
776 Goodra  |  Dragon
777 Klefki  |  Steel
778 Phantump  |  Ghost
779 Trevenant  |  Ghost
780 PumpkabooAverage Size  |  Ghost
781 PumpkabooSmall Size  |  Ghost
782 PumpkabooLarge Size  |  Ghost
783 PumpkabooSuper Size  |  Ghost
784 GourgeistAverage Size  |  Ghost
785 GourgeistSmall Size  |  Ghost
786 GourgeistLarge Size  |  Ghost
787 GourgeistSuper Size  |  Ghost
788 Bergmite  |  Ice
789 Avalugg  |  Ice
790 Noibat  |  Flying
791 Noivern  |  Flying
792 Xerneas  |  Fairy
793 Yveltal  |  Dark
794 Zygarde50% Forme  |  Dragon
795 Diancie  |  Rock
796 DiancieMega Diancie  |  Rock
797 HoopaHoopa Confined  |  Psychic
798 HoopaHoopa Unbound  |  Psychic
799 Volcanion  |  Fire

In [46]:
# Getting data in a specific location

# Can be used to filter data with conditions
# Gets data only where Type1 equals to "Fire"
df.loc[df["Type 1"] == "Fire"]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False
42,37,Vulpix,Fire,NaN,38,41,40,50,65,65,1,False
43,38,Ninetales,Fire,NaN,73,76,75,81,100,100,1,False
63,58,Growlithe,Fire,NaN,55,70,45,70,50,60,1,False
64,59,Arcanine,Fire,NaN,90,110,80,100,80,95,1,False
83,77,Ponyta,Fire,NaN,50,85,55,65,65,90,1,False
84,78,Rapidash,Fire,NaN,65,100,70,80,80,105,1,False
135,126,Magmar,Fire,NaN,65,95,57,100,85,93,1,False
147,136,Flareon,Fire,NaN,65,130,60,95,110,65,1,False
158,146,Moltres,Fire,Flying,90,100,90,125,85,90,1,True
169,155,Cyndaquil,Fire,NaN,39,52,43,60,50,65,2,False
170,156,Quilava,Fire,NaN,58,64,58,80,65,80,2,False
171,157,Typhlosion,Fire,NaN,78,84,78,109,85,100,2,False
236,218,Slugma,Fire,NaN,40,40,40,70,40,20,2,False
237,219,Magcargo,Fire,Rock,50,50,120,80,80,30,2,False
259,240,Magby,Fire,NaN,45,75,37,70,55,83,2,False
263,244,Entei,Fire,NaN,115,115,85,90,75,100,2,True
270,250,Ho-oh,Fire,Flying,106,130,90,110,154,90,2,True
276,255,Torchic,Fire,NaN,45,60,40,70,50,45,3,False
277,256,Combusken,Fire,Fighting,60,85,60,85,60,55,3,False
278,257,Blaziken,Fire,Fighting,80,120,70,110,70,80,3,False
279,257,BlazikenMega Blaziken,Fire,Fighting,80,160,80,130,80,100,3,False
352,322,Numel,Fire,Ground,60,60,40,65,45,35,3,False
353,323,Camerupt,Fire,Ground,70,100,70,105,75,40,3,False
354,323,CameruptMega Camerupt,Fire,Ground,70,120,100,145,105,20,3,False
355,324,Torkoal,Fire,NaN,70,85,140,85,70,20,3,False
435,390,Chimchar,Fire,NaN,44,58,44,58,44,61,4,False
436,391,Monferno,Fire,Fighting,64,78,52,78,52,81,4,False
437,392,Infernape,Fire,Fighting,76,104,71,104,71,108,4,False
518,467,Magmortar,Fire,NaN,75,95,67,125,95,83,4,False
542,485,Heatran,Fire,Steel,91,90,106,130,106,77,4,True
557,498,Tepig,Fire,NaN,65,63,45,45,45,45,5,False
558,499,Pignite,Fire,Fighting,90,93,55,70,55,55,5,False
559,500,Emboar,Fire,Fighting,110,123,65,100,65,65,5,False
572,513,Pansear,Fire,NaN,50,53,48,53,48,64,5,False
573,514,Simisear,Fire,NaN,75,98,63,98,63,101,5,False
614,554,Darumaka,Fire,NaN,70,90,45,15,45,50,5,False
615,555,DarmanitanStandard Mode,Fire,NaN,105,140,55,30,55,95,5,False
616,555,DarmanitanZen Mode,Fire,Psychic,105,30,105,140,105,55,5,False
692,631,Heatmor,Fire,NaN,85,97,66,105,66,65,5,False
721,653,Fennekin,Fire,NaN,40,45,40,62,60,60,6,False
722,654,Braixen,Fire,NaN,59,59,58,90,70,73,6,False
723,655,Delphox,Fire,Psychic,75,69,72,114,100,104,6,False
730,662,Fletchinder,Fire,Flying,62,73,55,56,52,84,6,False
731,663,Talonflame,Fire,Flying,78,81,71,74,69,126,6,False
735,667,Litleo,Fire,Normal,62,50,58,73,54,72,6,False
736,668,Pyroar,Fire,Normal,86,68,72,109,66,106,6,False
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [48]:
# Can be used to filter data with conditions
# Gets data only where Type1 equals to "Grass"
df.loc[df["Type 1"] == "Grass"]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
48,43,Oddish,Grass,Poison,45,50,55,75,65,30,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
718,650,Chespin,Grass,NaN,56,61,65,48,45,38,6,False
719,651,Quilladin,Grass,NaN,61,78,95,56,58,57,6,False
720,652,Chesnaught,Grass,Fighting,88,107,122,74,75,64,6,False
740,672,Skiddo,Grass,NaN,66,65,48,62,57,52,6,False
741,673,Gogoat,Grass,NaN,123,100,62,97,81,68,6,False

In [50]:
df.describe()

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [52]:
# Sorting dataframe depending on values
df.sort_values(by="Name", ascending=True)  # ascending = True Or False; False means descending

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
392,359,Absol,Dark,NaN,65,130,60,75,60,75,3,False
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...
632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False
631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True

In [54]:
# Sorting dataframe by multiple columns
df.sort_values(by=["Type 1", "HP"])  # ascending = True Or False; False means descending

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
316,292,Shedinja,Bug,Ghost,1,90,45,30,30,40,3,False
230,213,Shuckle,Bug,Rock,20,10,230,10,230,5,2,False
462,415,Combee,Bug,Flying,30,30,42,30,42,70,4,False
603,543,Venipede,Bug,Poison,30,45,59,30,39,57,5,False
314,290,Nincada,Bug,Ground,31,45,90,30,30,40,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...
142,131,Lapras,Water,Ice,130,85,80,85,95,60,1,False
145,134,Vaporeon,Water,NaN,130,65,60,110,95,65,1,False
350,320,Wailmer,Water,NaN,130,70,35,70,35,60,3,False
655,594,Alomomola,Water,NaN,165,75,80,40,45,65,5,False
351,321,Wailord,Water,NaN,170,90,45,90,45,60,3,False

In [55]:
# Sorting dataframe by multiple columns in ascending or descending order
df.sort_values(by=["Type 1", "HP"], ascending=True)  # ascending = True Or False; False means descending

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
316,292,Shedinja,Bug,Ghost,1,90,45,30,30,40,3,False
230,213,Shuckle,Bug,Rock,20,10,230,10,230,5,2,False
462,415,Combee,Bug,Flying,30,30,42,30,42,70,4,False
603,543,Venipede,Bug,Poison,30,45,59,30,39,57,5,False
314,290,Nincada,Bug,Ground,31,45,90,30,30,40,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...
142,131,Lapras,Water,Ice,130,85,80,85,95,60,1,False
145,134,Vaporeon,Water,NaN,130,65,60,110,95,65,1,False
350,320,Wailmer,Water,NaN,130,70,35,70,35,60,3,False
655,594,Alomomola,Water,NaN,165,75,80,40,45,65,5,False
351,321,Wailord,Water,NaN,170,90,45,90,45,60,3,False

In [57]:
# Sorting dataframe by multiple columns in one ascending and 2nd descending
# This means, Type 1 will be ascending and HP will be descending
df.sort_values(by=["Type 1", "HP"], ascending=[1, 0])  # [1= ascending, 0=descending]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
520,469,Yanmega,Bug,Flying,86,76,86,116,56,95,4,False
698,637,Volcarona,Bug,Fire,85,60,65,135,105,100,5,False
231,214,Heracross,Bug,Fighting,80,125,75,40,95,85,2,False
232,214,HeracrossMega Heracross,Bug,Fighting,80,185,115,40,105,75,2,False
678,617,Accelgor,Bug,NaN,80,70,40,100,60,145,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...
106,98,Krabby,Water,NaN,30,105,90,25,25,50,1,False
125,116,Horsea,Water,NaN,30,40,70,70,25,60,1,False
129,120,Staryu,Water,NaN,30,45,55,70,55,85,1,False
139,129,Magikarp,Water,NaN,20,10,55,15,20,80,1,False
381,349,Feebas,Water,NaN,20,15,20,10,55,80,3,False

## Making changes the data

In [59]:
# Adding new column with total of all HP, Attack, Defense, Sp. Atk, Sp. Defense, Speed
df['Total'] = df['HP'] + df["Attack"] + df["Defense"] + df["Sp. Atk"] + df["Sp. Def"] + df["Speed"]
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,600
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,700
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,680
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600

In [60]:
# Dropping some columns
df = df.drop(columns=["Total"])

df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [72]:
# adding column by calculating values dynamically
df['Total'] = df.iloc[:, 4:10].sum(axis=1)
df.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309

In [79]:
cols = list(df.columns.values)
cols

['#',
 'Name',
 'Type 1',
 'Type 2',
 'HP',
 'Attack',
 'Defense',
 'Sp. Atk',
 'Sp. Def',
 'Speed',
 'Generation',
 'Legendary',
 'Total']

In [90]:
cols[0:4]

['#', 'Name', 'Type 1', 'Type 2']

In [91]:
cols[-1]

'Total'

In [92]:
[cols[-1]]

['Total']

In [93]:
# Rearranging columns in different ways
# TypeError: can only concatenate list (not "str") to list
# df = df[cols[0:4] + cols[-1] + cols[4:-1]] # this line gives above error
# because cols[-1] returns the string 'Total' but we need an list to concatenate here
# Solution is to wrap it in list

TypeError: can only concatenate list (not "str") to list

In [97]:
# This method basically does rearranging by concatenation
# And we are overwriting the value of original variable with the concatenation result
df = df[cols[0:4] + [cols[-1]] + cols[4:-1]]  # this line gives above error
df

# Using this method might not be robust, as it depends on indexing, and if indexes changes due to any reason,
# The final result of data might be messed up.

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [105]:
# Write the data to a csv file
df.to_csv('../../data/modified_pokeman_data.csv', index=False)  # index=False will not save the index
# df.to_excel('../../../../data/modified_pokeman_data.csv', index=False)
df.to_csv('../../data/modified_pokeman_data.txt', index=False, sep='\t')

## Filtering Data

In [108]:
# And &
filtered_data = df.loc[(df["Type 1"] == "Grass") & (df["Type 2"] == "Poison")]
filtered_data

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
48,43,Oddish,Grass,Poison,320,45,50,55,75,65,30,1,False
49,44,Gloom,Grass,Poison,395,60,65,70,85,75,40,1,False
50,45,Vileplume,Grass,Poison,490,75,80,85,110,90,50,1,False
75,69,Bellsprout,Grass,Poison,300,50,75,35,70,30,40,1,False
76,70,Weepinbell,Grass,Poison,390,65,90,50,85,45,55,1,False
77,71,Victreebel,Grass,Poison,490,80,105,65,100,70,70,1,False
344,315,Roselia,Grass,Poison,400,50,60,45,100,80,65,3,False
451,406,Budew,Grass,Poison,280,40,30,35,50,70,55,4,False
452,407,Roserade,Grass,Poison,515,60,70,65,125,105,90,4,False
651,590,Foongus,Grass,Poison,294,69,55,45,55,55,15,5,False
652,591,Amoonguss,Grass,Poison,464,114,85,70,85,80,30,5,False

In [122]:
# OR |
filtered_data = df.loc[(df["Type 1"] == "Grass") | (df["Type 2"] == "Poison")]
filtered_data

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
16,13,Weedle,Bug,Poison,195,40,35,30,20,20,50,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
718,650,Chespin,Grass,NaN,313,56,61,65,48,45,38,6,False
719,651,Quilladin,Grass,NaN,405,61,78,95,56,58,57,6,False
720,652,Chesnaught,Grass,Fighting,530,88,107,122,74,75,64,6,False
740,672,Skiddo,Grass,NaN,350,66,65,48,62,57,52,6,False
741,673,Gogoat,Grass,NaN,531,123,100,62,97,81,68,6,False

In [123]:
# To reset index on filtered data,
# filtered_data = filtered_data.reset_index(drop=True) # drop=True will drop the old index
filtered_data.reset_index(drop=True,
                          inplace=True)  # drop=True, inplace=True will replace the original variable with new indices, so no need to reassign to same variable to overwrite
filtered_data

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,13,Weedle,Bug,Poison,195,40,35,30,20,20,50,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
84,650,Chespin,Grass,NaN,313,56,61,65,48,45,38,6,False
85,651,Quilladin,Grass,NaN,405,61,78,95,56,58,57,6,False
86,652,Chesnaught,Grass,Fighting,530,88,107,122,74,75,64,6,False
87,672,Skiddo,Grass,NaN,350,66,65,48,62,57,52,6,False
88,673,Gogoat,Grass,NaN,531,123,100,62,97,81,68,6,False

In [135]:
# in python ~ represents not operator
# filtering Names containing Mega
df.loc[df['Name'].str.contains('Mega')]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
12,9,BlastoiseMega Blastoise,Water,NaN,630,79,103,120,135,115,78,1,False
19,15,BeedrillMega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,579,83,80,80,135,80,121,1,False
71,65,AlakazamMega Alakazam,Psychic,NaN,590,55,50,65,175,95,150,1,False
87,80,SlowbroMega Slowbro,Water,Psychic,590,95,75,180,130,80,30,1,False
102,94,GengarMega Gengar,Ghost,Poison,600,60,65,80,170,95,130,1,False
124,115,KangaskhanMega Kangaskhan,Normal,NaN,590,105,125,100,60,100,100,1,False
137,127,PinsirMega Pinsir,Bug,Flying,600,65,155,120,65,90,105,1,False
141,130,GyaradosMega Gyarados,Water,Dark,640,95,155,109,70,130,81,1,False
154,142,AerodactylMega Aerodactyl,Rock,Flying,615,80,135,85,70,95,150,1,False
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,780,106,190,100,154,100,130,1,True
164,150,MewtwoMega Mewtwo Y,Psychic,NaN,780,106,150,70,194,120,140,1,True
168,154,Meganium,Grass,NaN,525,80,82,100,83,100,80,2,False
196,181,AmpharosMega Ampharos,Electric,Dragon,610,90,95,105,165,110,45,2,False
224,208,SteelixMega Steelix,Steel,Ground,610,75,125,230,55,95,30,2,False
229,212,ScizorMega Scizor,Bug,Steel,600,70,150,140,65,100,75,2,False
232,214,HeracrossMega Heracross,Bug,Fighting,600,80,185,115,40,105,75,2,False
248,229,HoundoomMega Houndoom,Dark,Fire,600,75,90,90,140,90,115,2,False
268,248,TyranitarMega Tyranitar,Rock,Dark,700,100,164,150,95,120,71,2,False
275,254,SceptileMega Sceptile,Grass,Dragon,630,70,110,75,145,85,145,3,False
279,257,BlazikenMega Blaziken,Fire,Fighting,630,80,160,80,130,80,100,3,False
283,260,SwampertMega Swampert,Water,Ground,635,100,150,110,95,110,70,3,False
306,282,GardevoirMega Gardevoir,Psychic,Fairy,618,68,85,65,165,135,100,3,False
327,302,SableyeMega Sableye,Dark,Ghost,480,50,85,125,85,115,20,3,False
329,303,MawileMega Mawile,Steel,Fairy,480,50,105,125,55,95,50,3,False
333,306,AggronMega Aggron,Steel,NaN,630,70,140,230,60,80,50,3,False
336,308,MedichamMega Medicham,Fighting,Psychic,510,60,100,85,80,85,100,3,False
339,310,ManectricMega Manectric,Electric,NaN,575,70,75,80,135,80,135,3,False
349,319,SharpedoMega Sharpedo,Water,Dark,560,70,140,70,110,65,105,3,False
354,323,CameruptMega Camerupt,Fire,Ground,560,70,120,100,145,105,20,3,False
366,334,AltariaMega Altaria,Dragon,Fairy,590,75,110,110,110,105,80,3,False
387,354,BanetteMega Banette,Ghost,NaN,555,64,165,75,93,83,75,3,False
393,359,AbsolMega Absol,Dark,NaN,565,65,150,60,115,60,115,3,False
397,362,GlalieMega Glalie,Ice,NaN,580,80,120,80,120,80,100,3,False
409,373,SalamenceMega Salamence,Dragon,Flying,700,95,145,130,120,90,120,3,False
413,376,MetagrossMega Metagross,Steel,Psychic,700,80,145,150,105,110,110,3,False
418,380,LatiasMega Latias,Dragon,Psychic,700,80,100,120,140,150,110,3,True
420,381,LatiosMega Latios,Dragon,Psychic,700,80,130,100,160,120,110,3,True
426,384,RayquazaMega Rayquaza,Dragon,Flying,780,105,180,100,180,100,115,3,True
476,428,LopunnyMega Lopunny,Normal,Fighting,580,65,136,94,54,96,135,4,False
494,445,GarchompMega Garchomp,Dragon,Ground,700,108,170,115,120,95,92,4,False
498,448,LucarioMega Lucario,Fighting,Steel,625,70,145,88,140,70,112,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,594,90,132,105,132,105,30,4,False
527,475,GalladeMega Gallade,Psychic,Fighting,618,68,165,95,65,115,110,4,False
591,531,AudinoMega Audino,Normal,Fairy,545,103,60,126,80,126,50,5,False
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True

In [136]:
# filtering Names not containing Mega
df.loc[~df['Name'].str.contains('Mega')]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
794,718,Zygarde50% Forme,Dragon,Ground,600,108,100,121,81,95,95,6,True
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [137]:
df.loc[df['Type 1'].str.contains('fire|grass', regex=True)]  # Case issue, grass|fire first letters should be capital

Empty DataFrame
Columns: [#, Name, Type 1, Type 2, Total, HP, Attack, Defense, Sp. Atk, Sp. Def, Speed, Generation, Legendary]
Index: []

In [138]:
# library contains regex flags
import re

df.loc[df['Type 1'].str.contains('fire|grass', flags=re.I, regex=True)]  # makes the regex flag to make it case insensitive

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,667,Litleo,Fire,Normal,369,62,50,58,73,54,72,6,False
736,668,Pyroar,Fire,Normal,507,86,68,72,109,66,106,6,False
740,672,Skiddo,Grass,NaN,350,66,65,48,62,57,52,6,False
741,673,Gogoat,Grass,NaN,531,123,100,62,97,81,68,6,False
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [139]:
# filtering name with regex
df.loc[df['Name'].str.contains('^pi.*', flags=re.I, regex=True)]  # makes the regex flag to make it case insensitive

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
20,16,Pidgey,Normal,Flying,251,40,45,40,35,35,56,1,False
21,17,Pidgeotto,Normal,Flying,349,63,60,55,50,50,71,1,False
22,18,Pidgeot,Normal,Flying,479,83,80,75,70,70,101,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,579,83,80,80,135,80,121,1,False
30,25,Pikachu,Electric,NaN,320,35,55,40,50,50,90,1,False
136,127,Pinsir,Bug,NaN,500,65,125,100,55,70,85,1,False
137,127,PinsirMega Pinsir,Bug,Flying,600,65,155,120,65,90,105,1,False
186,172,Pichu,Electric,NaN,205,20,40,15,35,35,60,2,False
219,204,Pineco,Bug,NaN,290,50,65,90,35,35,15,2,False
239,221,Piloswine,Ice,Ground,450,100,100,80,60,60,50,2,False
438,393,Piplup,Water,NaN,314,53,51,53,61,56,40,4,False
558,499,Pignite,Fire,Fighting,418,90,93,55,70,55,55,5,False
578,519,Pidove,Normal,Flying,264,50,55,50,36,30,43,5,False

## Conditional Changes

In [140]:
# Make a copy of the data frame
test_data = df.copy()

# Changes Legendary Value to True based on the Condition Type 1 == Fire
test_data.loc[test_data['Type 1'] == 'Fire', 'Legendary'] = True
test_data

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [143]:
test_data.loc[(test_data['Type 1'] == 'Fire') & (test_data['Legendary'] == False)]

Empty DataFrame
Columns: [#, Name, Type 1, Type 2, Total, HP, Attack, Defense, Sp. Atk, Sp. Def, Speed, Generation, Legendary]
Index: []

In [144]:
# a test copy of the data
dft = df.copy()

# Changing multiple values based on condition
dft.loc[dft['Total'] > 500, ['Generation', 'Legendary']] = 'Test Value'
# Changes both properties values to "Test Value"

dft

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,Test Value,Test Value
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,Test Value,Test Value
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,Test Value,Test Value
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,Test Value,Test Value
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,Test Value,Test Value
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,Test Value,Test Value
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,Test Value,Test Value

In [145]:
# Changing multiple values based on condition
dft.loc[dft['Total'] > 500, ['Generation', 'Legendary']] = ['Test 1', 'Test 2']
# Changes Generation to "Test 1" and Legendary to "Test 2"

dft

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,Test 1,Test 2
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,Test 1,Test 2
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,Test 1,Test 2
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,Test 1,Test 2
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,Test 1,Test 2
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,Test 1,Test 2
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,Test 1,Test 2

## Aggregate Statistics (Groupby)

In [148]:
dft = df.copy()

# dft.groupby(['Type 1']).mean().sort_values('Defense', ascending=False)

dft.groupby(['Type 1']).mean().sort_values('Attack', ascending=False)

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,,
Dragon,474.375000,550.531250,83.312500,112.125000,86.375000,96.843750,88.843750,83.031250,3.875000,0.375000
Fighting,363.851852,416.444444,69.851852,96.777778,65.925926,53.111111,64.703704,66.074074,3.370370,0.000000
Ground,356.281250,437.500000,73.781250,95.750000,84.843750,56.468750,62.750000,63.906250,3.156250,0.125000
Rock,392.727273,453.750000,65.363636,92.863636,100.795455,63.340909,75.477273,55.909091,3.454545,0.090909
Steel,442.851852,487.703704,65.222222,92.703704,126.370370,67.518519,80.629630,55.259259,3.851852,0.148148
Dark,461.354839,445.741935,66.806452,88.387097,70.225806,74.645161,69.516129,76.161290,4.032258,0.064516
Fire,327.403846,458.076923,69.903846,84.769231,67.769231,88.980769,72.211538,74.442308,3.211538,0.096154
Flying,677.750000,485.000000,70.750000,78.750000,66.250000,94.250000,72.500000,102.500000,5.500000,0.500000
Poison,251.785714,399.142857,67.250000,74.678571,68.821429,60.428571,64.392857,63.571429,2.535714,0.000000
Water,303.089286,430.455357,72.062500,74.151786,72.946429,74.812500,70.517857,65.964286,2.857143,0.035714
Ghost,486.500000,439.562500,64.437500,73.781250,81.187500,79.343750,76.468750,64.343750,4.187500,0.062500
Normal,319.173469,401.683673,77.275510,73.469388,59.846939,55.816327,63.724490,71.551020,3.051020,0.020408
Grass,344.871429,421.142857,67.271429,73.214286,70.800000,77.500000,70.428571,61.928571,3.357143,0.042857
Ice,423.541667,433.458333,72.000000,72.750000,71.416667,77.541667,76.291667,63.458333,3.541667,0.083333
Psychic,380.807018,475.947368,70.631579,71.456140,67.684211,98.403509,86.280702,81.491228,3.385965,0.245614
Bug,334.492754,378.927536,56.884058,70.971014,70.724638,53.869565,64.797101,61.681159,3.217391,0.000000
Electric,363.500000,443.409091,59.795455,69.090909,66.295455,90.022727,73.704545,84.500000,3.272727,0.090909
Fairy,449.529412,413.176471,74.117647,61.529412,65.705882,78.529412,84.705882,48.588235,4.117647,0.058824

In [158]:
dft = df.copy()

# Different functions applying on groupby
# dft.groupby(['Type 1']).sum()

# dft['count'] = 1
dft['count'] = 1
dft

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,count
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,1
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,1
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,1
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,1
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,1
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,1
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,1
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,1
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,1

In [165]:
# type(dft.groupby(['Type 1']))
dft.groupby(['Type 1']).count()['count']

pandas.core.groupby.generic.DataFrameGroupBy

In [169]:
dft.groupby(['Type 1', 'Type 2']).count()['count']

# dft.groupby(['Type 2', 'Type 1']).count()['count']

Type 1  Type 2
Bug     Electric     2
        Fighting     2
        Fire         2
        Flying      14
        Ghost        1
                    ..
Water   Ice          3
        Poison       3
        Psychic      5
        Rock         4
        Steel        1
Name: count, Length: 136, dtype: int64

## Working with large amounts of data

In [170]:
# reading csv in chunks
for dfc in pd.read_csv('../../data/pokemon_data.csv', chunksize=5):
    print("Chunk DF")
    print(dfc)

# Reading file in chunks can be useful if the dataset is too large
# in the loop we can read the data and store it after shrinking it e.g. groupBy,
# or only if a certain condition is met e.g. dat == "useful" store it, else discard it.

Chunk DF
   #                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1              Bulbasaur  Grass  Poison  45      49       49       65
1  2                Ivysaur  Grass  Poison  60      62       63       80
2  3               Venusaur  Grass  Poison  80      82       83      100
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122
4  4             Charmander   Fire     NaN  39      52       43       60

   Sp. Def  Speed  Generation  Legendary
0       65     45           1      False
1       80     60           1      False
2      100     80           1      False
3      120     80           1      False
4       50     65           1      False
Chunk DF
   #                       Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
5  5                 Charmeleon   Fire     NaN  58      64       58       80
6  6                  Charizard   Fire  Flying  78      84       78      109
7  6  CharizardMega Charizard X   Fire  Dragon  78     130      111      130
8  6  CharizardMega Charizard Y   Fire  Flying  78     104       78      159
9  7                   Squirtle  Water     NaN  44      48       65       50

   Sp. Def  Speed  Generation  Legendary
5       65     80           1      False
6       85    100           1      False
7       85    100           1      False
8      115    100           1      False
9       64     43           1      False
Chunk DF
     #                     Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
10   8                Wartortle  Water     NaN  59      63       80       65
11   9                Blastoise  Water     NaN  79      83      100       85
12   9  BlastoiseMega Blastoise  Water     NaN  79     103      120      135
13  10                 Caterpie    Bug     NaN  45      30       35       20
14  11                  Metapod    Bug     NaN  50      20       55       25

    Sp. Def  Speed  Generation  Legendary
10       80     58           1      False
11      105     78           1      False
12      115     78           1      False
13       20     45           1      False
14       25     30           1      False
Chunk DF
     #                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
15  12             Butterfree    Bug  Flying  60      45       50       90
16  13                 Weedle    Bug  Poison  40      35       30       20
17  14                 Kakuna    Bug  Poison  45      25       50       25
18  15               Beedrill    Bug  Poison  65      90       40       45
19  15  BeedrillMega Beedrill    Bug  Poison  65     150       40       15

    Sp. Def  Speed  Generation  Legendary
15       80     70           1      False
16       20     50           1      False
17       25     35           1      False
18       80     75           1      False
19       80    145           1      False
Chunk DF
     #                 Name  Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
20  16               Pidgey  Normal  Flying  40      45       40       35
21  17            Pidgeotto  Normal  Flying  63      60       55       50
22  18              Pidgeot  Normal  Flying  83      80       75       70
23  18  PidgeotMega Pidgeot  Normal  Flying  83      80       80      135
24  19              Rattata  Normal     NaN  30      56       35       25

    Sp. Def  Speed  Generation  Legendary
20       35     56           1      False
21       50     71           1      False
22       70    101           1      False
23       80    121           1      False
24       35     72           1      False
Chunk DF
     #      Name  Type 1  Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  \
25  20  Raticate  Normal     NaN  55      81       60       50       70
26  21   Spearow  Normal  Flying  40      60       30       31       31
27  22    Fearow  Normal  Flying  65      90       65       61       61
28  23     Ekans  Poison     NaN  35      60       44       40       54
29  24     Arbok  Poison     NaN  60      85       69       65       79

    Speed  Generation  Legendary
25     97           1      False
26     70           1      False
27    100           1      False
28     55           1      False
29     80           1      False
Chunk DF
     #              Name    Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
30  25           Pikachu  Electric     NaN  35      55       40       50
31  26            Raichu  Electric     NaN  60      90       55       90
32  27         Sandshrew    Ground     NaN  50      75       85       20
33  28         Sandslash    Ground     NaN  75     100      110       45
34  29  Nidoran (Female)    Poison     NaN  55      47       52       40

    Sp. Def  Speed  Generation  Legendary
30       50     90           1      False
31       80    110           1      False
32       30     40           1      False
33       55     65           1      False
34       40     41           1      False
Chunk DF
     #            Name  Type 1  Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  \
35  30        Nidorina  Poison     NaN  70      62       67       55       55
36  31       Nidoqueen  Poison  Ground  90      92       87       75       85
37  32  Nidoran (Male)  Poison     NaN  46      57       40       40       40
38  33        Nidorino  Poison     NaN  61      72       57       55       55
39  34        Nidoking  Poison  Ground  81     102       77       85       75

    Speed  Generation  Legendary
35     56           1      False
36     76           1      False
37     50           1      False
38     65           1      False
39     85           1      False
Chunk DF
     #        Name  Type 1 Type 2   HP  Attack  Defense  Sp. Atk  Sp. Def  \
40  35    Clefairy   Fairy    NaN   70      45       48       60       65
41  36    Clefable   Fairy    NaN   95      70       73       95       90
42  37      Vulpix    Fire    NaN   38      41       40       50       65
43  38   Ninetales    Fire    NaN   73      76       75       81      100
44  39  Jigglypuff  Normal  Fairy  115      45       20       45       25

    Speed  Generation  Legendary
40     35           1      False
41     60           1      False
42     65           1      False
43    100           1      False
44     20           1      False
Chunk DF
     #        Name  Type 1  Type 2   HP  Attack  Defense  Sp. Atk  Sp. Def  \
45  40  Wigglytuff  Normal   Fairy  140      70       45       85       50
46  41       Zubat  Poison  Flying   40      45       35       30       40
47  42      Golbat  Poison  Flying   75      80       70       65       75
48  43      Oddish   Grass  Poison   45      50       55       75       65
49  44       Gloom   Grass  Poison   60      65       70       85       75

    Speed  Generation  Legendary
45     45           1      False
46     55           1      False
47     90           1      False
48     30           1      False
49     40           1      False
Chunk DF
     #       Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  \
50  45  Vileplume  Grass  Poison  75      80       85      110       90
51  46      Paras    Bug   Grass  35      70       55       45       55
52  47   Parasect    Bug   Grass  60      95       80       60       80
53  48    Venonat    Bug  Poison  60      55       50       40       55
54  49   Venomoth    Bug  Poison  70      65       60       90       75

    Speed  Generation  Legendary
50     50           1      False
51     25           1      False
52     30           1      False
53     45           1      False
54     90           1      False
Chunk DF
     #     Name  Type 1  Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  \
55  50  Diglett  Ground     NaN  10      55       25       35       45     95
56  51  Dugtrio  Ground     NaN  35      80       50       50       70    120
57  52   Meowth  Normal     NaN  40      45       35       40       40     90
58  53  Persian  Normal     NaN  65      70       60       65       65    115
59  54  Psyduck   Water     NaN  50      52       48       65       50     55

    Generation  Legendary
55           1      False
56           1      False
57           1      False
58           1      False
59           1      False
Chunk DF
     #       Name    Type 1  Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  \
60  55    Golduck     Water     NaN  80      82       78       95       80
61  56     Mankey  Fighting     NaN  40      80       35       35       45
62  57   Primeape  Fighting     NaN  65     105       60       60       70
63  58  Growlithe      Fire     NaN  55      70       45       70       50
64  59   Arcanine      Fire     NaN  90     110       80      100       80

    Speed  Generation  Legendary
60     85           1      False
61     70           1      False
62     95           1      False
63     60           1      False
64     95           1      False
Chunk DF
     #       Name   Type 1    Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  \
65  60    Poliwag    Water       NaN  40      50       40       40       40
66  61  Poliwhirl    Water       NaN  65      65       65       50       50
67  62  Poliwrath    Water  Fighting  90      95       95       70       90
68  63       Abra  Psychic       NaN  25      20       15      105       55
69  64    Kadabra  Psychic       NaN  40      35       30      120       70

    Speed  Generation  Legendary
65     90           1      False
66     90           1      False
67     70           1      False
68     90           1      False
69    105           1      False
Chunk DF
     #                   Name    Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
70  65               Alakazam   Psychic     NaN  55      50       45      135
71  65  AlakazamMega Alakazam   Psychic     NaN  55      50       65      175
72  66                 Machop  Fighting     NaN  70      80       50       35
73  67                Machoke  Fighting     NaN  80     100       70       50
74  68                Machamp  Fighting     NaN  90     130       80       65

    Sp. Def  Speed  Generation  Legendary
70       95    120           1      False
71       95    150           1      False
72       35     35           1      False
73       60     45           1      False
74       85     55           1      False
Chunk DF
     #        Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  \
75  69  Bellsprout  Grass  Poison  50      75       35       70       30
76  70  Weepinbell  Grass  Poison  65      90       50       85       45
77  71  Victreebel  Grass  Poison  80     105       65      100       70
78  72   Tentacool  Water  Poison  40      40       35       50      100
79  73  Tentacruel  Water  Poison  80      70       65       80      120

    Speed  Generation  Legendary
75     40           1      False
76     55           1      False
77     70           1      False
78     70           1      False
79    100           1      False
Chunk DF
     #      Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  \
80  74   Geodude   Rock  Ground  40      80      100       30       30     20
81  75  Graveler   Rock  Ground  55      95      115       45       45     35
82  76     Golem   Rock  Ground  80     120      130       55       65     45
83  77    Ponyta   Fire     NaN  50      85       55       65       65     90
84  78  Rapidash   Fire     NaN  65     100       70       80       80    105

    Generation  Legendary
80           1      False
81           1      False
82           1      False
83           1      False
84           1      False
Chunk DF
     #                 Name    Type 1   Type 2  HP  Attack  Defense  Sp. Atk  \
85  79             Slowpoke     Water  Psychic  90      65       65       40
86  80              Slowbro     Water  Psychic  95      75      110      100
87  80  SlowbroMega Slowbro     Water  Psychic  95      75      180      130
88  81            Magnemite  Electric    Steel  25      35       70       95
89  82             Magneton  Electric    Steel  50      60       95      120

    Sp. Def  Speed  Generation  Legendary
85       40     15           1      False
86       80     30           1      False
87       80     30           1      False
88       55     45           1      False
89       70     70           1      False
Chunk DF
     #        Name  Type 1  Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  \
90  83  Farfetch'd  Normal  Flying  52      65       55       58       62
91  84       Doduo  Normal  Flying  35      85       45       35       35
92  85      Dodrio  Normal  Flying  60     110       70       60       60
93  86        Seel   Water     NaN  65      45       55       45       70
94  87     Dewgong   Water     Ice  90      70       80       70       95

    Speed  Generation  Legendary
90     60           1      False
91     75           1      False
92    100           1      False
93     45           1      False
94     70           1      False
Chunk DF
     #      Name  Type 1  Type 2   HP  Attack  Defense  Sp. Atk  Sp. Def  \
95  88    Grimer  Poison     NaN   80      80       50       40       50
96  89       Muk  Poison     NaN  105     105       75       65      100
97  90  Shellder   Water     NaN   30      65      100       45       25
98  91  Cloyster   Water     Ice   50      95      180       85       45
99  92    Gastly   Ghost  Poison   30      35       30      100       35

    Speed  Generation  Legendary
95     25           1      False
96     50           1      False
97     40           1      False
98     70           1      False
99     80           1      False
Chunk DF
      #               Name   Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
100  93            Haunter    Ghost  Poison  45      50       45      115
101  94             Gengar    Ghost  Poison  60      65       60      130
102  94  GengarMega Gengar    Ghost  Poison  60      65       80      170
103  95               Onix     Rock  Ground  35      45      160       30
104  96            Drowzee  Psychic     NaN  60      48       45       43

     Sp. Def  Speed  Generation  Legendary
100       55     95           1      False
101       75    110           1      False
102       95    130           1      False
103       45     70           1      False
104       90     42           1      False
Chunk DF
       #       Name    Type 1  Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  \
105   97      Hypno   Psychic     NaN  85      73       70       73      115
106   98     Krabby     Water     NaN  30     105       90       25       25
107   99    Kingler     Water     NaN  55     130      115       50       50
108  100    Voltorb  Electric     NaN  40      30       50       55       55
109  101  Electrode  Electric     NaN  60      50       70       80       80

     Speed  Generation  Legendary
105     67           1      False
106     50           1      False
107     75           1      False
108    100           1      False
109    140           1      False
Chunk DF
       #       Name    Type 1   Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  \
110  102  Exeggcute     Grass  Psychic  60      40       80       60       45
111  103  Exeggutor     Grass  Psychic  95      95       85      125       65
112  104     Cubone    Ground      NaN  50      50       95       40       50
113  105    Marowak    Ground      NaN  60      80      110       50       80
114  106  Hitmonlee  Fighting      NaN  50     120       53       35      110

     Speed  Generation  Legendary
110     40           1      False
111     55           1      False
112     35           1      False
113     45           1      False
114     87           1      False
Chunk DF
       #        Name    Type 1 Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  \
115  107  Hitmonchan  Fighting    NaN  50     105       79       35      110
116  108   Lickitung    Normal    NaN  90      55       75       60       75
117  109     Koffing    Poison    NaN  40      65       95       60       45
118  110     Weezing    Poison    NaN  65      90      120       85       70
119  111     Rhyhorn    Ground   Rock  80      85       95       30       30

     Speed  Generation  Legendary
115     76           1      False
116     30           1      False
117     35           1      False
118     60           1      False
119     25           1      False
Chunk DF
       #                       Name  Type 1 Type 2   HP  Attack  Defense  \
120  112                     Rhydon  Ground   Rock  105     130      120
121  113                    Chansey  Normal    NaN  250       5        5
122  114                    Tangela   Grass    NaN   65      55      115
123  115                 Kangaskhan  Normal    NaN  105      95       80
124  115  KangaskhanMega Kangaskhan  Normal    NaN  105     125      100

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
120       45       45     40           1      False
121       35      105     50           1      False
122      100       40     60           1      False
123       40       80     90           1      False
124       60      100    100           1      False
Chunk DF
       #     Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  \
125  116   Horsea  Water     NaN  30      40       70       70       25
126  117   Seadra  Water     NaN  55      65       95       95       45
127  118  Goldeen  Water     NaN  45      67       60       35       50
128  119  Seaking  Water     NaN  80      92       65       65       80
129  120   Staryu  Water     NaN  30      45       55       70       55

     Speed  Generation  Legendary
125     60           1      False
126     85           1      False
127     63           1      False
128     68           1      False
129     85           1      False
Chunk DF
       #        Name    Type 1   Type 2  HP  Attack  Defense  Sp. Atk  \
130  121     Starmie     Water  Psychic  60      75       85      100
131  122    Mr. Mime   Psychic    Fairy  40      45       65      100
132  123     Scyther       Bug   Flying  70     110       80       55
133  124        Jynx       Ice  Psychic  65      50       35      115
134  125  Electabuzz  Electric      NaN  65      83       57       95

     Sp. Def  Speed  Generation  Legendary
130       85    115           1      False
131      120     90           1      False
132       80    105           1      False
133       95     95           1      False
134       85    105           1      False
Chunk DF
       #               Name  Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
135  126             Magmar    Fire     NaN  65      95       57      100
136  127             Pinsir     Bug     NaN  65     125      100       55
137  127  PinsirMega Pinsir     Bug  Flying  65     155      120       65
138  128             Tauros  Normal     NaN  75     100       95       40
139  129           Magikarp   Water     NaN  20      10       55       15

     Sp. Def  Speed  Generation  Legendary
135       85     93           1      False
136       70     85           1      False
137       90    105           1      False
138       70    110           1      False
139       20     80           1      False
Chunk DF
       #                   Name  Type 1  Type 2   HP  Attack  Defense  \
140  130               Gyarados   Water  Flying   95     125       79
141  130  GyaradosMega Gyarados   Water    Dark   95     155      109
142  131                 Lapras   Water     Ice  130      85       80
143  132                  Ditto  Normal     NaN   48      48       48
144  133                  Eevee  Normal     NaN   55      55       50

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
140       60      100     81           1      False
141       70      130     81           1      False
142       85       95     60           1      False
143       48       48     48           1      False
144       45       65     55           1      False
Chunk DF
       #      Name    Type 1 Type 2   HP  Attack  Defense  Sp. Atk  Sp. Def  \